resources:
  repositories:
    #    - repository: PaasPrometheusExporter # The name used to reference this repository in the checkout step
    #      type: github
    #      name: alphagov/paas-prometheus-exporter
    - repository: templates
      type: git
      name: pinc/azure-pipeline-templates
      ref: refs/heads/master

variables:
  - template: build-variables.yml@templates

jobs:
  - job: "build"
    pool:
      vmImage: "ubuntu-latest"

    steps:
      - task: Docker@2
        displayName: Login to docker.na1.hsdp.io
        inputs:
          command: login
          containerRegistry: docker.na1.hsdp.io

      - script: |
          docker buildx build -f Dockerfile -t docker.na1.hsdp.io/phm-services/dm-cf-crontab:latest .
          docker push docker.na1.hsdp.io/phm-services/dm-cf-crontab:latest
        displayName: 'Download Paas Prometheus Exporter'
